[package]
name = "r_assignment1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.95.1"
nalgebra = "0.33.2"
bitflags = "2.9.1"
